### PR TITLE
Publish DoorSensorStateName to mqtt

### LINKED ISSUE #29: Enable Doorsensor States
Hi @bluewalk,

still very happy with NukiBridge2Mqtt. Thanks!

It would be nice to see the [new Doorsensor States](https://developer.nuki.io/page/nuki-bridge-http-api-1-11/4/#heading--doorsensor-states) also implemented.  Nuki just [released ](https://developer.nuki.io/t/bridge-beta-fw-2-6-0-1-16-0-with-door-sensor-state/6159/13) this a few days ago

Thanks dickesW

### PR DESCRIPTION
**Pull request by dickesW**
Fixes #29

### CODE REVIEW

**Comment by bluewalk** [comment]
Agreed, those were missing. Thanks! 👍

**Comment by dickesW** [comment]
Cool, are you pushing a new release?
Just saw that there is a blank to much in the code I added. Will this be a problem?

**Comment by bluewalk** [comment]
No that won't be a problem, also decided to publish the enum value to the mqtt topic.
New image is being built at Docker Hub as we speak.

**Comment by dickesW** [comment]
Works for the Nuki Lock, but seems to break the Opener mqtt messages. The lockState API Call for the Opener does not contain the values for doorstate:
`{
    "mode": 2,
    "state": 1,
    "stateName": "online",
    "batteryCritical": false,
    "success": true
}`

**Comment by bluewalk** [comment]
That's okay, if the JSON doesn't contain the required fields it should have no problem deserializing the object.
Are you getting a specific error?

**Comment by dickesW** [comment]
my bad - looked into the wrong mqtt topic :) Works as designed ;-)

**Comment by dickesW** [comment]
door-state for the opener is 0 - btw

**Comment by bluewalk** [comment]
> 
> 
> my bad - looked into the wrong mqtt topic :) Works as designed ;-)
Thanks, good to hear
> 
> 
> door-state for the opener is 0 - btw
I have added the state Unknown (0) in the develop branch, will be included in the next release

**Pull request merged**
